### ISSUE TITLE
Error compiling on M1 mac for android phone

### ISSUE THREAD

**Issue by Antonio-Melo** [dev-family/react-native-device-country#5] opened 2023-01-04 22:14 UTC
As soon as I compile with the package, this error occurs.
Works great for iOS, but not for Android.

<img width="1133" alt="Screenshot 2023-01-04 at 22 11 40" src="https://user-images.githubusercontent.com/13281300/210659862-9ad0cda1-7707-4d51-bf7c-01ea4ef9751c.png">

**Comment by gofurnazarov** [comment] 2023-01-24 10:05
I have the same issue. Anybody has a solution?

**Comment by gofurnazarov** [comment] 2023-01-24 11:49
Finally found the solution. The problem is because of that I am targeting Sdk API 31 but  `react-native-device-country` is targeting Sdk API 29. I changed to 31 `node_modules/react-native-device-country/android/build.gradle` file:

```
android {
    compileSdkVersion safeExtGet('DeviceCountry_compileSdkVersion', 31)
    buildToolsVersion safeExtGet('DeviceCountry_buildToolsVersion', '31')
    defaultConfig {
        minSdkVersion safeExtGet('DeviceCountry_minSdkVersion', 16)
        targetSdkVersion safeExtGet('DeviceCountry_targetSdkVersion', 31)
        versionCode 1
        versionName "1.0"

    }
...
```

The issue already fixed on github repo but the update has not been published to npm.

**Comment by mshekspirtt** [comment] 2023-01-24 12:10
Thank you. Version 1.0.3 published to npm.

**Closed as completed by mshekspirtt** 2023-01-24 12:10 UTC
